services:

  db:
    image: mariadb
    restart: always
    ports:
      - 3306:3306
    volumes:
      - dbvolume:/var/lib/mysql
    environment:
      MARIADB_ROOT_PASSWORD: freelance
      MARIADB_USER: freelance
      MARIADB_PASSWORD: freelance
      MARIADB_DATABASE: freelance
    
  app:
    build: .
    restart: always
    ports:
      - 80:80
    env_file: .env
    depends_on:
      - db

volumes:
  dbvolume: